package com.api.database.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "user_history")
public class UserHistoryDao {
    private String id;
    private String userEmail;
    private int product;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "Email")
    public String getUserEmail() {
        return userEmail;
    }

    @DynamoDBAttribute(attributeName = "Product")
    public int getProduct() {
        return product;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public void setProduct(int product) {
        this.product = product;
    }

    public UserHistoryDao(String userEmail, int productId) {
        this.userEmail = userEmail;
        this.product = productId;
    }

    public UserHistoryDao(){}

}

